### ISSUE TITLE
Internet-Explorer 11 / unknown error: MaskedTextBox

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-inputs#5]
Hi,

the MaskedTextBox doesn't run under Internet-Explorer 11.

Error: Unbekannter Fehler.
   at setMaskValue (http://localhost:54963/dist/app.bundle.js:56665:13)
   at applyMask (http://localhost:54963/dist/app.bundle.js:56015:5)
   at MaskedTextBox.prototype.resetMaskedTextBox (http://localhost:54963/dist/app.bundle.js:56876:9)
   at MaskedTextBox.prototype.render (http://localhost:54963/dist/app.bundle.js:56859:13)
   at Component.prototype.appendTo (http://localhost:54963/dist/app.bundle.js:42558:13)
   at Anonymous function (http://localhost:54963/dist/app.bundle.js:219866:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:54963/dist/polyfills.bundle.js:9079:13)
   at onInvokeTask (http://localhost:54963/dist/app.bundle.js:4953:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:54963/dist/polyfills.bundle.js:9079:13)
   at Zone.prototype.runTask (http://localhost:54963/dist/polyfills.bundle.js:8848:21)

Version: "@syncfusion/ej2-ng-inputs": "16.1.28",

Regards
j.nord

**Comment by rajendranr-5483** [comment]
@j-nord , We have validated your reported issue in "@syncfusion/ej2-ng-inputs": "16.1.28" version using IE11 browser, but we could not reproduce the issue in our end. Also, we have prepared a simple sample for this scenario.

Sample: https://plnkr.co/edit/RNH5sTMIhFiqnHKFAiCH?p=preview 

If you are still facing the issue could you please share more details to reproduce the issue in our end or modify given sample for reproducing the issue? It will be helpful for us to provide a better solution as early as possible.

**Comment by j-nord** [comment]
Hi,

We have a big project and get the error in every mask. 

We have bootstrap 4 template and the masktextbox in a custom Control.

So it doesn't run.

Regards
j.nord

**Comment by rajendranr-5483** [comment]
@j-nord , We have validated your reported issue with mentioned scenario “bootstrap 4 template and the masktextbox in a custom Control”. But we unable to reproduce the issue (unknown error: MaskedTextBox) in our end. 

For your reference, we have prepared a sample in the link: 
http://plnkr.co/edit/KRtErapCR3EGClrs9H7w?p=preview

We suspect that the reported issue occurs due to mask format and value are mismatched. So, could you please share the below details? It will be helpful for us to provide an appropriate solution.
1.	Mask format value defined in app component (_maskFormat)
2.	Value defined in app component (value)

If possible, please modify the above Plunker sample and revert to us to reproduce the issue in our end.
Regards,
Rajendran R

**Comment by j-nord** [comment]
Hi Rajendran,

your example is not the same. You doesn't use @Input().

    @Input()
    set placeholder(value: string) {
        this._placeholder = value;
    }

    @Input()
    set tooltip(value: string) {
        this._tooltip = value;
    }
    
    @Input()
    set label(value: string) {
        this._label = value;
        //this._placeholder = !(this._placeholder) ? value : this._placeholder;
    };

    @Input()
    set width(value: string) {
        this._width = value;
    }
       
    @Input()
    set maskFormat(value: string) {
        this._maskFormat = value;
    }

and we have found the next problem:

the "this.onChangeCallback" function doesn't work with your control. We have searched one day to find out that the maskedtextbox not really work under angular5. We have tested under angular 5.1.0 and 5.2.9

You can see this, when you have a really custom control and check the "set value" routine in the debugger .

Regards
j.nord

**Comment by soundarapandianr** [comment]
@j-nord, based on your information, we had modified the sample with @Input decorators, also used the angular version 5.2.9 only. Still, we are unable to reproduce the reported issue. Please refer the below updated sample:
http://plnkr.co/edit/mFk3RDXBlswgspyBAcfN?p=preview

If still you are facing the same problem then we request you to create a support ticket through the below link:
http://www.syncfusion.com/Account/Logon?ReturnUrl=%2fsupport%2fdirecttrac 

Or sent the details to Syncfusion support(support@syncfusion.com). 

So that we can arrange a web meeting to resolve the issue.   

Regards,
Soundar

**Comment by j-nord** [comment]
Hi Soundar,

there are differences between our Project and your project. We use webpack and polyfills.ts for IE and not shim.

``

**Comment by soundarapandianr** [comment]
@j-nord, Based on your comments we have modified the sample with using "webpack" and “polyfills.ts” file. Please check the below updated sample and let us know your comments.
 
[Sample](https://github.com/syncfusion/ej2-ng-inputs/files/1851303/Mask_Demo.zip)
 
If still you are facing the same problem then we request you to create a support ticket.
 
Regards,
Soundar
